### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by maciejmiara** [dgnet/Conferia#10]
Especially on later stages of project it would be great to have continuous integration.
Travis CI is free for open-source projects.
Any other ideas?

**Comment by michalpipa** [comment]
Definitely we want to use travis. When we will have anything to test, we will integrate with travis.

**Comment by zibios** [comment]
I suggest also [SensioLabsInsight](https://insight.sensiolabs.com/) and [scrutinizer](https://scrutinizer-ci.com/)
