### ISSUE TITLE
Features first 

### ISSUE THREAD

**Issue by norberttech** [dgnet/Conferia#4]
1. Remove current bundle 
2. Start with user stories
3. Implement user stories only with domain code
4. Integrate code from domain with Sf2 framework.

**Comment by alanbem** [comment]
x. Extract domain into external repository and integrate with different framework just to prove that framework agnosticity is possible :)

**Comment by daryush** [comment]
+1

**Comment by tabbi89** [comment]
@norzechowicz `3. Implement user stories only with domain code` how You plan here to designate/discuss context boundaries ?

**Comment by norberttech** [comment]
I think we should focus on core features list first, just to know what we are dealing with.

**Comment by marek-pietrzak-tg** [comment]
+1

**Comment by daryush** [comment]
Some of concepts are placed in this prezentation created by @DarGrze http://www.dgnet.pl/prez-conferia.pdf

**Comment by l-bujakowski** [comment]
+1

**Comment by tabbi89** [comment]
@pskt we are waiting for more specific information in order to start :)

**Comment by cakper** [comment]
I'd suggest following some more established process of defining requirements. Impact mapping makes sense to me: http://impactmapping.org/index.php

**Comment by l3l0** [comment]
@cakper Yeah can work. Only problem I can see is that we are quite distributed and remote team. We can try to use https://www.mindmup.com for impact mapping session but first let's do some hangout/skype call with all interested ppl and try to organize ourself. We can create some chat like hipchat or flowdock one - this helps most of the time in remote communication as well.

**Comment by cakper** [comment]
We can try to use Slack for non profit :)

**Comment by tciunelis** [comment]
+1 for communication :)

**Comment by marek-pietrzak-tg** [comment]
+1 for slack - way better than hipchat

**Comment by norberttech** [comment]
Yea hipchat sucks, I would love to give a try to slack : )

**Comment by maciejmiara** [comment]
+1 for slack

**Comment by marek-pietrzak-tg** [comment]
OK guys, I've created slack account for Conferia, just need your e-mail addresses to send invitations :smile:

**Comment by l3l0** [comment]
@mheki leszek.prabucki@gmail.com

**Comment by l-bujakowski** [comment]
@mheki l.bujakowski@gmail.com

**Comment by maciejmiara** [comment]
@mheki mkowalski8+conferia@gmail.com
I think, that @DarGrze should have admin access, this is his project

**Comment by dariuszwrzesien** [comment]
dariuszwrzesien@gmail.com

**Comment by tciunelis** [comment]
@mheki tytus.ciunelis@gmail.com

**Comment by tabbi89** [comment]
@mheki tom@tabbi89.com

**Comment by alanbem** [comment]
@mheki alan.bem+conferia@gmail.com

**Comment by daryush** [comment]
@mheki dariusz.drobisz@gmail.com

**Comment by zibios** [comment]
@mheki zibios@gmail.com

**Comment by daryush** [comment]
ping @mheki add my mail to conferia slack please and also grant @DarGrze admin permissions
