### ISSUE TITLE
Testing tools

### ISSUE THREAD

**Issue by marek-pietrzak-tg** [dgnet/Conferia#5]
Would be nice to agree which testing tools will be used in the project.
I'd suggest:
- phpspec to drive code implementation
- behat for user stories

**Comment by tabbi89** [comment]
For some kind of Integration tests I prefer using phpUnit

**Comment by marek-pietrzak-tg** [comment]
:+1:  @tabbi89 phpunit is better for integration tests. 
However I'd used all of above tools for different purposes.

**Comment by matiangul** [comment]
:+1: @mheki

**Comment by zibios** [comment]
@mheki :+1: 
PhpUnit sometimes it is irreplaceable

**Comment by timiTao** [comment]
:+1:  good approach is to have all level of tests.
Behat(functionality)  + phpUnit should be good
